name: build and push docker image
on:
  workflow_run:
    workflows: [build and test, CodeQL]
    types:
      - completed
jobs:
  release-docker:
    name: Release docker image
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -o alertapi -v

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sundock2020/alert_manager

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: sundock2020/alert_manager
          push: true
